spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:mem:maindb
    username: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        format_sql: true
