spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:mem:maindb;MODE=LEGACY;
#    MODE=LEGACY используется, так как в новых версиях H2 исчезла функция IDENTITY().
#    Из-за этого падает JdbcMutableAclService.createOrRetrieveSidPrimaryKey
#    На команде return (Long)this.jdbcOperations.queryForObject(this.sidIdentityQuery, Long.class);
#    Как альтернатива - писать кастомный JdbcMutableAclService и обходить вызов IDENTITY
    username: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update

    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
