spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/PFM
    username: postgres
    password: 2305
  sql:
    init:
      mode: never
#      data-locations: data.sql
#      schema-locations: schema.sql

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        format_sql: true
