spring:
  data:
    mongodb:
      host: localhost
      database: library_db
      port: 32768

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
